// 🎯 BotTargetRandomizer.java
// @Generated by ChatGPT — Охотник за случайной целью 😎

package com.devone.bot.core.logic.navigation;

import java.util.List;
import java.util.Random;

import com.devone.bot.utils.blocks.BotBlockData;

public class BotTargetRandomizer {

    private static final Random RANDOM = new Random();

    /**
     * Выбирает случайную точку из списка.
     *
     * @param targets список доступных точек
     * @return одна случайная точка или null, если список пуст или null
     */
    public static BotBlockData pickRandomTarget(List<BotBlockData> targets) {
        if (targets == null || targets.isEmpty()) {
            return null;
        }
        int index = RANDOM.nextInt(targets.size());
        return targets.get(index);
    }
}
