// @Generated by ChatGPT – reachability for the seekers of paths 😎

package com.devone.bot.core.logic.navigation.evaluators;

import com.devone.bot.utils.blocks.BotBlockData;
import com.devone.bot.utils.blocks.BotLocation;

import java.util.*;
import java.util.stream.Collectors;

public class BotTargetReachabilityEvaluator {

    /**
     * Проверяет, достижима ли конкретная точка target из позиции botPosition,
     * основываясь на списке навигационно проходимых точек.
     */
    public static boolean isReachable(BotLocation botPosition,
                                      BotLocation target,
                                      List<BotBlockData> navigablePoints) {
        if (botPosition.equals(target)) return true;

        Set<String> visited = new HashSet<>();
        Queue<BotLocation> queue = new LinkedList<>();
        queue.add(botPosition);
        visited.add(coordKey(botPosition));

        Set<String> navigableSet = navigablePoints.stream()
                .map(BotTargetReachabilityEvaluator::coordKey)
                .collect(Collectors.toSet());

        while (!queue.isEmpty()) {
            BotLocation current = queue.poll();

            for (int dx = -1; dx <= 1; dx++) {
                for (int dy = -1; dy <= 1; dy++) {
                    for (int dz = -1; dz <= 1; dz++) {
                        if (Math.abs(dx) + Math.abs(dy) + Math.abs(dz) != 1) continue;

                        BotLocation neighbor = new BotLocation(
                                current.getX() + dx,
                                current.getY() + dy,
                                current.getZ() + dz);

                        String key = coordKey(neighbor);
                        if (!navigableSet.contains(key) || visited.contains(key)) continue;

                        if (neighbor.equals(target)) return true;

                        visited.add(key);
                        queue.add(neighbor);
                    }
                }
            }
        }

        return false;
    }

    private static String coordKey(BotLocation c) {
        return c.toString();
    }
}
