// 🧭 BotNavigationPlannerWrapper.java
// @Generated by ChatGPT — Путеводная нить логики и разведки 😎

package com.devone.bot.core.navigation;

import com.devone.bot.core.navigation.BotExplorationTargetPlanner.Strategy;
import com.devone.bot.utils.BotBlockData;
import com.devone.bot.utils.BotCoordinate3D;

import java.util.List;

public class BotNavigationPlannerWrapper {

    /**
     * Основной метод: выбирает цели разведки на основе достигнутых точек.
     * Использует стратегию EVEN_DISTRIBUTED, автоматический scanRadius и безопасный возврат.
     *
     * @param botPosition - текущая позиция бота
     * @param reachable - список достижимых точек
     * @param sectorCount - количество секторов (например, 24)
     * @param maxTargets - максимум точек для возврата
     * @return список целевых точек или null, если целей нет
     */
    public static List<BotBlockData> getNextExplorationTargets(BotCoordinate3D botPosition,
                                                                List<BotBlockData> reachable,
                                                                int sectorCount,
                                                                int maxTargets) {
        if (reachable == null || reachable.isEmpty()) return null;

        int scanRadius = estimateSafeScanRadius(botPosition, reachable, 10); // авто-оценка, с дефолтом

        List<BotBlockData> targets = BotExplorationTargetPlanner.selectTargets(
                botPosition,
                reachable,
                Strategy.EVEN_DISTRIBUTED,
                sectorCount,
                maxTargets,
                true,       // предпочитаем дальние
                scanRadius  // радиус сканирования
        );

        return (targets == null || targets.isEmpty()) ? null : targets;
    }

    /**
     * Расчёт безопасного радиуса сканирования на основе максимально удалённой точки.
     */
    private static int estimateSafeScanRadius(BotCoordinate3D bot, List<BotBlockData> reachable, int defaultRadius) {
        double maxDistSq = 0;
        for (BotBlockData b : reachable) {
            double dx = b.x - bot.x;
            double dy = b.y - bot.y;
            double dz = b.z - bot.z;
            double distSq = dx * dx + dy * dy + dz * dz;
            if (distSq > maxDistSq) {
                maxDistSq = distSq;
            }
        }
        return Math.max(2, (int) Math.sqrt(maxDistSq));
    }
}
